In [1]:
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[6, 23], [-1, 7], [8, 9]])

x

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [3]:
# x.dot(y) é equivalente a np.dot(x, y)
x.dot(y) # multiplicação de matrizes (linha x coluna)

array([[ 28,  64],
       [ 67, 181]])

In [4]:
# Um produto de matrizes entre um array bidimensional e um array unidimensional resulta em um array unidimensional
x @ np.ones(3) # Lembrando que o @ significa multiplicacao

array([ 6., 15.])

In [5]:
np.ones(3)

array([1., 1., 1.])

In [6]:
# numpy.linalg tem um conjunto padráo de decomposicao de matrizes e operacoes como inverso e determinante
from numpy.linalg import inv, qr
rng = np.random.default_rng()

X = rng.standard_normal((5, 5))

In [7]:
X

array([[ 0.27633188,  0.86652365,  1.29131748, -0.52916508,  0.43447336],
       [ 1.49779654,  1.05412218,  0.58100615,  0.97826562,  1.0788634 ],
       [ 1.18631555,  0.45687803, -0.69463794, -1.06540984,  2.74484396],
       [ 0.67849071, -2.30787031, -0.19915772, -0.34846004,  0.01391842],
       [-0.38924669, -0.13019172,  0.74479563, -0.51251852, -1.77453244]])

In [8]:
mat = X.T @ X

In [9]:
inv(mat) # inverse of a matrix

array([[ 1.61398868,  0.59903737, -1.03261053, -0.59778606, -1.14559367],
       [ 0.59903737,  0.45646801, -0.57431104, -0.32495879, -0.52556334],
       [-1.03261053, -0.57431104,  1.18278356,  0.45129408,  0.87549639],
       [-0.59778606, -0.32495879,  0.45129408,  0.64654947,  0.50358217],
       [-1.14559367, -0.52556334,  0.87549639,  0.50358217,  0.95302264]])

In [10]:
mat

array([[ 4.33896101,  0.84511829, -0.02203449,  0.01817465,  5.69240218],
       [ 0.84511829,  7.4139896 ,  1.77670775,  0.95684134,  2.96670168],
       [-0.02203449,  1.77670775,  3.08197517,  0.31280927, -2.0432394 ],
       [ 0.01817465,  0.95684134,  0.31280927,  2.75621708, -1.1942462 ],
       [ 5.69240218,  2.96670168, -2.0432394 , -1.1942462 , 12.03604079]])

In [11]:
mat @ inv(mat)

array([[ 1.00000000e+00,  9.49856288e-16,  3.27358219e-16,
        -4.82487002e-16,  6.09080322e-16],
       [-1.83552520e-17,  1.00000000e+00, -1.08498564e-15,
        -5.09218439e-17, -3.79939478e-16],
       [ 2.87104533e-16, -1.46606393e-16,  1.00000000e+00,
        -4.83633002e-17, -4.26807629e-16],
       [-2.41061444e-16,  1.29538759e-16, -8.50146169e-17,
         1.00000000e+00,  1.14690255e-16],
       [ 1.89963960e-16,  4.04530620e-16, -1.59100668e-15,
         2.16369710e-16,  1.00000000e+00]])

In [12]:
np.round(mat @ inv(mat))

array([[ 1.,  0.,  0., -0.,  0.],
       [-0.,  1., -0., -0., -0.],
       [ 0., -0.,  1., -0., -0.],
       [-0.,  0., -0.,  1.,  0.],
       [ 0.,  0., -0.,  0.,  1.]])

In [20]:
np.array([2, 4]) @ np.array([3, 4]) # (2 x 3) + (4 x 4)

np.int64(22)