## Diferença de tempo entre um array numpy e uma lista (ambos com 1 milhão de inteiros)

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(5_000_000)

my_list = list(range(5_000_000))

In [3]:
%timeit my_arr2 = my_arr * 2

9.42 ms ± 73.2 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
%timeit my_list2 = [x * 2 for x in my_list]

277 ms ± 23.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
test_arr = np.arange(10)

In [6]:
test_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.

## Computação em lote com NumPy - Algumas operações padrões

In [8]:
data = np.array([[1, 2, 3],[3.5, 7, 4]])

In [9]:
data

array([[1. , 2. , 3. ],
       [3.5, 7. , 4. ]])

In [10]:
data * 10

array([[10., 20., 30.],
       [35., 70., 40.]])

In [11]:
data + data

array([[ 2.,  4.,  6.],
       [ 7., 14.,  8.]])

In [12]:
# Chegar dimensao do array
data.shape

(2, 3)

In [13]:
# Chegar type do array
data.dtype

dtype('float64')

## Convertendo uma lista para ndarray

In [15]:
lst = [1, 7, 4, 2.5, 3.7]
arr = np.array(lst)

In [16]:
arr

array([1. , 7. , 4. , 2.5, 3.7])

In [17]:
# Sequencias aninhadas (lista de lista) ira criar um array multidimensional
lst2 = [[3.4, 2.7, 3],[2.1, 2, 4]]
arr2 = np.array(lst2)
arr2

array([[3.4, 2.7, 3. ],
       [2.1, 2. , 4. ]])

In [18]:
# Chegar numero de dimensoes do array
arr2.ndim

2

In [19]:
arr2.shape

(2, 3)

## Criando arrays pre-definidos com 0's 1's e sem tamanho

In [22]:
# É possível criar um array de zeros com a funcao zeros(n)
arr_z = np.zeros(10) # Neste caso sera criado um array unidimensional com 10 valores zerados
arr_z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
# Porém é possível multidimensionar um array de zeros passando uma tupla com a dimensao desejada
arr_z_multi = np.zeros((2, 4))
arr_z_multi

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
# np.empty vai criar um array sem inicializa-lo especificamente
np.empty((2, 3, 2)) # Não é seguro afirmar que será criado um array somente com zeros, np.empty pode pegar valores sujos da memória

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [26]:
# Também existe a opcao de criar um array somente com 1's
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# O np.full criara um array com o shape e o valor padrao passados
np.full(3, 2)

array([2, 2, 2])

In [32]:
np.full((4,5), 'bb') # Cria um array multidimensional 4 por 5 com valores definidos como 'bb'

array([['bb', 'bb', 'bb', 'bb', 'bb'],
       ['bb', 'bb', 'bb', 'bb', 'bb'],
       ['bb', 'bb', 'bb', 'bb', 'bb'],
       ['bb', 'bb', 'bb', 'bb', 'bb']], dtype='<U2')