## Diferença de tempo entre um array numpy e uma lista (ambos com 1 milhão de inteiros)

In [1]:
import numpy as np

In [2]:
my_arr = np.arange(5_000_000)

my_list = list(range(5_000_000))

In [3]:
%timeit my_arr2 = my_arr * 2

9.42 ms ± 73.2 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
%timeit my_list2 = [x * 2 for x in my_list]

277 ms ± 23.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [5]:
test_arr = np.arange(10)

In [6]:
test_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.

## Computação em lote com NumPy - Algumas operações padrões

In [8]:
data = np.array([[1, 2, 3],[3.5, 7, 4]])

In [9]:
data

array([[1. , 2. , 3. ],
       [3.5, 7. , 4. ]])

In [10]:
data * 10

array([[10., 20., 30.],
       [35., 70., 40.]])

In [11]:
data + data

array([[ 2.,  4.,  6.],
       [ 7., 14.,  8.]])

In [12]:
# Chegar dimensao do array
data.shape

(2, 3)

In [13]:
# Chegar type do array
data.dtype

dtype('float64')

## Convertendo uma lista para ndarray

Um array é mais performático que uma lista comum do python (built-in list).
Como os arrays do NumPy são implementados com libs de C isso aumenta o desempenho.
Isso permite a estes arrays executar operações vetoriais por todos os elementos sem a necessidade de utilizar um loop (for)


In [15]:
lst = [1, 7, 4, 2.5, 3.7]
arr = np.array(lst)

In [16]:
arr

array([1. , 7. , 4. , 2.5, 3.7])

In [17]:
# Sequencias aninhadas (lista de lista) ira criar um array multidimensional
lst2 = [[3.4, 2.7, 3],[2.1, 2, 4]]
arr2 = np.array(lst2)
arr2

array([[3.4, 2.7, 3. ],
       [2.1, 2. , 4. ]])

In [18]:
# Chegar numero de dimensoes do array
arr2.ndim

2

In [19]:
arr2.shape

(2, 3)

## Criando arrays pre-definidos com 0's 1's e sem tamanho

In [22]:
# É possível criar um array de zeros com a funcao zeros(n)
arr_z = np.zeros(10) # Neste caso sera criado um array unidimensional com 10 valores zerados
arr_z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
# Porém é possível multidimensionar um array de zeros passando uma tupla com a dimensao desejada
arr_z_multi = np.zeros((2, 4))
arr_z_multi

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
# np.empty vai criar um array sem inicializa-lo especificamente
np.empty((2, 3, 2)) # Não é seguro afirmar que será criado um array somente com zeros, np.empty pode pegar valores sujos da memória

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [26]:
# Também existe a opcao de criar um array somente com 1's
np.ones(5)

array([1., 1., 1., 1., 1.])

In [27]:
np.ones((4, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# O np.full criara um array com o shape e o valor padrao passados
np.full(3, 2)

array([2, 2, 2])

In [32]:
np.full((4,5), 'bb') # Cria um array multidimensional 4 por 5 com valores definidos como 'bb'

array([['bb', 'bb', 'bb', 'bb', 'bb'],
       ['bb', 'bb', 'bb', 'bb', 'bb'],
       ['bb', 'bb', 'bb', 'bb', 'bb'],
       ['bb', 'bb', 'bb', 'bb', 'bb']], dtype='<U2')

In [40]:
# Cria uma matriz identidiade quadrada N x N
np.eye(10)
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Aritmética com arrays NumPy

Os arrays são importantes porque permitem expressar operações em lote com dados sem ser preciso escrever nenhum loop for. Os usuários do NumPy chamam isso de vetorização

In [2]:
import numpy as np
arr = np.array([[1, 2, 3],[4, 5, 6]])

In [12]:
arr

array([[ 3,  7, 12],
       [ 2,  3,  9]])

In [4]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [5]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [7]:
# As operações aritméticas escalares propagam o argumento escalar para cada elemento do array, como na divisão abaixo
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [8]:
arr ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [17]:
# As comparações entre arrays do mesmo tamanho gera arrays booleanos
arr = np.array([[1, 2, 3],[4, 5, 6]])
arr2 = np.array([[3, 7, 12],[2, 5, 9]])

arr == arr2

array([[False, False, False],
       [False,  True, False]])

In [18]:
arr != arr2

array([[ True,  True,  True],
       [ True, False,  True]])

In [19]:
arr > arr2

array([[False, False, False],
       [ True, False, False]])

In [20]:
arr >= arr2

array([[False, False, False],
       [ True,  True, False]])

In [22]:
# Fatiamento e acesso a indice de arrays unidimensionais é muito similar com os tipos built-in do python
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr[8]

np.int64(8)

In [24]:
arr[2:6]

array([2, 3, 4, 5])

In [26]:
arr[2:-3]

array([2, 3, 4, 5, 6])

In [29]:
# Valor 12 foi propagado (feito um broadcast) para as chaves abaixo
arr[5:8] = 12

In [28]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

### Uma diferança inicial importante em relação às listas internas do Python é que as fatias dos arrays são visualizações do array original. Isso significa que os dados não são copiados e qualqeur modificação feita na visualização será refletida no array de origem.

### No exemplo abaixo, copiamos uma fatia do array original para *arr_slice*. Quando modificarmos arr_slice essas modificações serão refletidas em *arr*

In [31]:
arr_slice = arr[2:4]
arr_slice

array([2, 3])

In [32]:
arr_slice[1] = 400
arr_slice

array([  2, 400])

In [33]:
arr

array([  0,   1,   2, 400,   4,  12,  12,  12,   8,   9])

### A fatia vazia [:] faz atribuição a todos os elementos de um array

In [34]:
arr_slice[:] = 24

In [35]:
arr_slice

array([24, 24])

In [36]:
arr

array([ 0,  1, 24, 24,  4, 12, 12, 12,  8,  9])

In [38]:
# Formas diferentes de acessar indices de arrays
arr = np.array([['a', 'b', 'c'], ['d', 'e', 'f']])
arr[0][2]

np.str_('c')

In [39]:
arr[0, 2]

np.str_('c')

### É importante ressaltas que o fatiamento em arrays multidimensionais o comportamento é diferente de como fatiar uma lista por exemplo

In [43]:
arr_multi = np.array([[[2, 3, 7],[9, 4, 22], [1, 3, 15]],[[6, 2, 1], [5, 15, 3], [0, 3, 6]]])

In [45]:
arr_multi.shape

(2, 3, 3)

In [52]:
# Pega as duas dimensões e somente a segunda linha de cada
arr_multi[:2, 1]

array([[ 9,  4, 22],
       [ 5, 15,  3]])

In [54]:
# Pega as duas dimensões e somente a última linha
arr_multi[:2, 2]

array([[ 1,  3, 15],
       [ 0,  3,  6]])

In [56]:
arr_multi[:2, 1:]

array([[[ 9,  4, 22],
        [ 1,  3, 15]],

       [[ 5, 15,  3],
        [ 0,  3,  6]]])

In [60]:
import numpy as nd
arr2d = nd.array([[1,2,3],[4,5,6],[7,8,9]])

In [61]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
# Pega as duas primeiras linhas
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
# pega as duas primeiras linhas a partir do indice 1, excluindo (1, 4)
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [65]:
# Pega apenas os elementos da terceira linha
arr2d[2:, :]

array([[7, 8, 9]])

In [68]:
# Pega apenas o primeiro e segundo elemento da segunda linha
arr2d[1:2, :2]

array([[4, 5]])